### ISSUE TITLE
Solution du problème de call API SSR/mode client => nginx

### ISSUE THREAD

**Issue by mmarchois** [fairnesscoop/permacoop#127]
Conf nginx :
```
upstream client {
    server client:3000;
}

upstream www {
	server www:8080;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://client;
    }

    location /api {
        proxy_pass http://www;
    }
}
```

Docker compose :
```
nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
```
